### ISSUE TITLE
How Do I Perform a Tag Search?

### ISSUE THREAD

**Issue by coommark** [vespassassina-zz/.NET-Instagram-API-Wrapper#1]
Hello! In the tag search, how do you pass in the access token? From where is it obtained?

**Comment by vespassassina-zz** [comment]
Instagram uses a OAuth 2 authentication scheme (like twitter, facebook and others), this means that you have to:

1- create an instagram application on instagram website and add the app token to your webapp
2- add your website callback address, the address that their website will send the user after authentication (this means that it should be accessible by internet users)
3- on authentication request, on your site, you have to send your user to IG authentication page 
4- the user will come back to your site, from IG site, with an authentication token
5- use this token to do stuff.

read this paper to get more info: http://instagram.com/developer/authentication/
